name: Self Hosted Runner | Ubuntu

on:
  workflow_dispatch:

env:
  DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
  PG_VERSION: 16

jobs:
  check-pg-versions:
    runs-on: self-hosted

    steps:
      - name: Set non-interactive frontend for apt
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo "DEBIAN_FRONTEND set to non-interactive"

      - name: Install PostgreSQL Common Package
        run: |
          echo "Running sudo apt update..."
          sudo -n apt update -y
          sudo -n apt install -y postgresql-common

      - name: Install PostgreSQL
        run: |
          echo "Running PostgreSQL install..."
          yes '' | sudo -n /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo -n apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Set PostgreSQL binary path
        run: |
          echo "POSTGRES=/usr/lib/postgresql/${{ env.PG_VERSION }}/bin" >> $GITHUB_ENV
          echo "Setting PostgreSQL binary path"

      - name: PostgreSQL version
        run: |
          "$POSTGRES/psql" "$DEV_DATABASE_URL" -c "SELECT version();"

      - name: Check psql Version
        run: |
          echo "Checking PostgreSQL version..."
          $POSTGRES/psql --version
